'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'az' | 'ru' | 'en';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  en: {
    choose_language: 'Choose language',
    azerbaijani: 'Azerbaijani',
    russian: 'Russian',
    english: 'English',
    search_placeholder: 'Search for anything...',
    categories: 'Categories',
    recent_listings: 'Recent Listings',
    home: 'Home',
    create: 'Create',
    profile: 'Profile',
    settings: 'Settings',
    language: 'Language',
    region: 'Region',
    currency: 'Currency',
    theme: 'Theme',
    notifications: 'Notifications',
    help_support: 'Help & Support',
    about: 'About',
    log_out: 'Log out',
    create_new_listing: 'Create new listing',
    category: 'Category',
    select_category: 'Select category',
    price: 'Price',
    description: 'Description',
    describe_item: 'Describe your item...',
    add_photos: 'Add Photos',
    publish_listing: 'Publish Listing',
    storage: 'Storage',
    ram: 'RAM',
    model: 'Model',
    type: 'Type',
    engineVolume: 'Engine volume',
    year: 'Year',
    mileage: 'Mileage',
    color: 'Color',
    condition: 'Condition',
    delivery: 'Delivery',
    new: 'New',
    used: 'Used',
    available: 'Available',
    not_available: 'Not available',
    black: 'Black',
    white: 'White',
    silver: 'Silver',
    gold: 'Gold',
    blue: 'Blue',
    red: 'Red',
    green: 'Green',
    gray: 'Gray',
    other: 'Other',
    listings: 'Listings',
    packages: 'Packages',
    stats: 'Stats',
    next: 'Next',
    skip: 'Skip',
    start_selling: 'Start Selling',
    phone_number: 'Phone Number',
    continue: 'Continue',
    verify: 'Verify',
    enter_code: 'Enter code sent to',
    resend_code: 'Resend code',
    connect_platforms: 'Connect Platforms',
    connected: 'Connected',
    connect: 'Connect',
    success: 'Success!',
    listing_published: 'Your listing has been published successfully.',
    view_listing: 'View Listing',
    back_to_home: 'Back to Home',
    my_listings: 'My Listings',
    active: 'Active',
    sold: 'Sold',
    archived: 'Archived',
    statistics: 'Statistics',
    total_views: 'Total Views',
    total_likes: 'Total Likes',
    total_messages: 'Total Messages',
    choose_plan: 'Choose Plan',
    free: 'Free',
    premium: 'Premium',
    pro: 'Pro',
    select: 'Select',
    current_plan: 'Current Plan',
    upgrade: 'Upgrade',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    start_title: 'Sell your products across multiple marketplaces with Salex.',
    start_subtitle: 'Post once and automatically share everywhere.',
    start: 'START',
    create_account: 'Create account',
    full_name: 'Full name',
    enter_full_name: 'Enter your full name',
    account_type: 'Account type',
    individual_seller: 'Individual seller',
    business_store: 'Business store',
    onboarding_title: 'Start selling easier with Salex.',
    onboarding_subtitle: 'Add your product once and publish everywhere.',
    connect_marketplaces: 'Connect marketplaces',
    connect_platforms_subtitle: 'Connect your marketplace accounts to start automating.',
    available_platforms: 'Available platforms',
    ready_to_connect: 'Ready to connect',
    coming_soon: 'Coming soon',
    locked: 'Locked',
    available_to_connect: 'Available to connect',
    connect_your_account: 'Connect your account',
    send_verification_code: 'Send verification code',
    enter_verification_code: 'Enter verification code',
    we_sent_code: 'We sent a 4-digit code to your phone',
    connected_success: 'connected',
    account_linked: 'Your account is successfully linked.',
    done: 'Done',
    registration_completed: 'Registration completed.',
    platforms_ready: 'Platforms are ready.',
    create_first_listing: 'Create your first listing',
    city: 'City',
    select_city: 'Select city',
    baku: 'Baku',
    ganja: 'Ganja',
    sumqayit: 'Sumqayit',
    shaki: 'Shaki',
    lankaran: 'Lankaran',
    images_upload: 'Images upload',
    share_platforms: 'Share platforms',
    model_name: 'Model name',
    enter_model: 'Enter model',
    brand_name: 'Brand name',
    enter_brand: 'Enter brand',
    congratulations: 'Congratulations',
    go_to_dashboard: 'Go to dashboard',
    todays_limit: "Today's limit",
    limit_reached: 'Limit reached',
    see_all: 'See all',
    no_listings_yet: 'No listings yet',
    create_first_listing_desc: 'Create your first listing to start selling across platforms',
    reset_limit: 'Reset limit (Debug)',
    todays_limit_reached: "Today's limit reached",
    limit_reached_desc: "You have reached today's listing limit.",
    view_packages: 'View packages',
    repost: 'Repost',
    choose_plan_desc: 'Choose the best plan for your sales.',
    basic_plan: 'Basic',
    per_week: '/ week',
    listings_per_day: '3 listings per day',
    activate: 'Activate',
    popular: 'Popular',
    premium_plan: 'Premium',
    priority_posting: 'Priority posting',
    full_statistics: 'Full statistics',
    auto_refresh: 'Auto-refresh listings',
    activate_premium: 'Activate Premium',
    premium_plus_plan: 'Premium+',
    per_month: '/ month',
    unlimited_listings: 'Unlimited listings',
    all_platforms: 'All platforms',
    business_tools: 'Business tools',
    activate_premium_plus: 'Activate Premium+',
    active_listings: 'Active Listings',
    views_by_platform: 'Views by Platform',
    top_performing: 'Top Performing',
    views_this_week: 'views this week',
    share_plan: 'Share plan',
    published_on: 'Your listing will be published on',
    inactive: 'Inactive',
    limit_indicator: 'Limit indicator:',
    listings_count: '1 / 3 listings',
    publishing: 'Publishing...',
    processing: 'processing',
    upload_images: 'Upload images',
    add_images_desc: 'Add at least 3 images. Drag and drop to reorder.',
    add_more_images: 'Add {count} more image(s)',
    ready_to_publish: 'Ready to publish!',
    active_plan: 'Active Plan',
    search: 'Search',
    enter_location: 'Enter location',
    search_city_district_or_address: 'Enter city, district, or address',
    screen_not_found: 'Screen not found',
    listing_actions: 'Listing actions',
    enter_value: 'Enter value',
    select_brand: 'Select brand',
    search_brand: 'Search brand',
    brand_required: 'Brand is required.',
    district: 'District',
    select_district: 'Select district',
    select_city_first: 'Select a city first',
  },
  az: {
    choose_language: 'Dil seçin',
    azerbaijani: 'Azərbaycan',
    russian: 'Rus',
    english: 'İngilis',
    search_placeholder: 'Hər hansı bir şey axtarın...',
    categories: 'Kateqoriyalar',
    recent_listings: 'Son elanlar',
    home: 'Ana səhifə',
    create: 'Yarat',
    profile: 'Profil',
    settings: 'Tənzimləmələr',
    language: 'Dil',
    region: 'Region',
    currency: 'Valyuta',
    theme: 'Mövzu',
    notifications: 'Bildirişlər',
    help_support: 'Kömək və dəstək',
    about: 'Haqqında',
    log_out: 'Çıxış',
    create_new_listing: 'Yeni elan yarat',
    category: 'Kateqoriya',
    select_category: 'Kateqoriya seçin',
    price: 'Qiymət',
    description: 'Təsvir',
    describe_item: 'Məhsulunuzu təsvir edin...',
    add_photos: 'Şəkil əlavə et',
    publish_listing: 'Elanı yayımla',
    storage: 'Yaddaş',
    ram: 'RAM',
    model: 'Model',
    type: 'Növ',
    engineVolume: 'Mühərrik həcmi',
    year: 'Buraxılış ili',
    mileage: 'Yürüş',
    color: 'Rəng',
    condition: 'Vəziyyəti',
    delivery: 'Çatdırılma',
    new: 'Yeni',
    used: 'İşlənmiş',
    available: 'Var',
    not_available: 'Yoxdur',
    black: 'Qara',
    white: 'Ağ',
    silver: 'Gümüşü',
    gold: 'Qızılı',
    blue: 'Mavi',
    red: 'Qırmızı',
    green: 'Yaşıl',
    gray: 'Boz',
    other: 'Digər',
    listings: 'Elanlar',
    packages: 'Paketlər',
    stats: 'Statistika',
    next: 'Növbəti',
    skip: 'Keç',
    start_selling: 'Satışa başla',
    phone_number: 'Telefon nömrəsi',
    continue: 'Davam et',
    verify: 'Təsdiqlə',
    enter_code: 'Göndərilən kodu daxil edin',
    resend_code: 'Kodu yenidən göndər',
    connect_platforms: 'Platformaları bağla',
    connected: 'Bağlandı',
    connect: 'Bağla',
    success: 'Uğurlu!',
    listing_published: 'Elanınız uğurla yayımlandı.',
    view_listing: 'Elana bax',
    back_to_home: 'Ana səhifəyə qayıt',
    my_listings: 'Mənim elanlarım',
    active: 'Aktiv',
    sold: 'Satıldı',
    archived: 'Arxivləndi',
    statistics: 'Statistika',
    total_views: 'Ümumi baxış',
    total_likes: 'Ümumi bəyənmə',
    total_messages: 'Ümumi mesaj',
    choose_plan: 'Plan seçin',
    free: 'Pulsuz',
    premium: 'Premium',
    pro: 'Pro',
    select: 'Seç',
    current_plan: 'Cari plan',
    upgrade: 'Yenilə',
    cancel: 'Ləğv et',
    save: 'Yadda saxla',
    edit: 'Düzəliş et',
    delete: 'Sil',
    confirm: 'Təsdiqlə',
    yes: 'Bəli',
    no: 'Xeyr',
    start_title: 'Məhsullarınızı Salex ilə bir çox platformada satın.',
    start_subtitle: 'Bir dəfə paylaşın və avtomatik olaraq hər yerdə yayımlansın.',
    start: 'BAŞLA',
    create_account: 'Hesab yarat',
    full_name: 'Ad və Soyad',
    enter_full_name: 'Ad və soyadınızı daxil edin',
    account_type: 'Hesab növü',
    individual_seller: 'Fərdi satıcı',
    business_store: 'Biznes mağazası',
    onboarding_title: 'Salex ilə satmaq daha asandır.',
    onboarding_subtitle: 'Məhsulunuzu bir dəfə əlavə edin və hər yerdə yayımlayın.',
    connect_marketplaces: 'Marketpleysləri bağla',
    connect_platforms_subtitle: 'Avtomatlaşdırmaya başlamaq üçün marketpleys hesablarınızı bağlayın.',
    available_platforms: 'Mövcud platformalar',
    ready_to_connect: 'Bağlanmağa hazırdır',
    coming_soon: 'Tezliklə',
    locked: 'Bağlıdır',
    available_to_connect: 'Bağlanmaq üçün mövcuddur',
    connect_your_account: 'Hesabınızı bağlayın',
    send_verification_code: 'Təsdiq kodunu göndər',
    enter_verification_code: 'Təsdiq kodunu daxil edin',
    we_sent_code: 'Telefonunuza 4 rəqəmli kod göndərdik',
    connected_success: 'bağlandı',
    account_linked: 'Hesabınız uğurla əlaqələndirildi.',
    done: 'Hazırdır',
    registration_completed: 'Qeydiyyat tamamlandı.',
    platforms_ready: 'Platformalar hazırdır.',
    create_first_listing: 'İlk elanınızı yaradın',
    city: 'Şəhər',
    select_city: 'Şəhər seçin',
    baku: 'Bakı',
    ganja: 'Gəncə',
    sumqayit: 'Sumqayıt',
    shaki: 'Şəki',
    lankaran: 'Lənkəran',
    images_upload: 'Şəkil yüklə',
    share_platforms: 'Platformalarda paylaş',
    model_name: 'Model adı',
    enter_model: 'Model yazın',
    brand_name: 'Marka adı',
    enter_brand: 'Marka yazın',
    congratulations: 'Təbriklər',
    go_to_dashboard: 'İdarə panelinə keç',
    todays_limit: 'Bugünkü limit',
    limit_reached: 'Limit bitdi',
    see_all: 'Hamısına bax',
    no_listings_yet: 'Hələ elan yoxdur',
    create_first_listing_desc: 'Platformalarda satışa başlamaq üçün ilk elanınızı yaradın',
    reset_limit: 'Limiti sıfırla (Debug)',
    todays_limit_reached: 'Bugünkü limit bitdi',
    limit_reached_desc: 'Siz bugünkü elan limitinə çatmısınız.',
    view_packages: 'Paketlərə bax',
    repost: 'Yenidən paylaş',
    choose_plan_desc: 'Satışlarınız üçün ən yaxşı planı seçin.',
    basic_plan: 'Baza',
    per_week: '/ həftə',
    listings_per_day: 'Gündə 3 elan',
    activate: 'Aktivləşdir',
    popular: 'Populyar',
    premium_plan: 'Premium',
    priority_posting: 'Prioritetli paylaşım',
    full_statistics: 'Tam statistika',
    auto_refresh: 'Elanların avtomatik yenilənməsi',
    activate_premium: 'Premiumu aktivləşdir',
    premium_plus_plan: 'Premium+',
    per_month: '/ ay',
    unlimited_listings: 'Limitsiz elan',
    all_platforms: 'Bütün platformalar',
    business_tools: 'Biznes alətləri',
    activate_premium_plus: 'Premium+ aktivləşdir',
    active_listings: 'Aktiv elanlar',
    views_by_platform: 'Platformalara görə baxış',
    top_performing: 'Ən çox baxılan',
    views_this_week: 'baxış bu həftə',
    share_plan: 'Paylaşım planı',
    published_on: 'Elanınız bu platformalarda yayımlanacaq',
    inactive: 'Aktiv deyil',
    limit_indicator: 'Limit göstəricisi:',
    listings_count: '1 / 3 elan',
    publishing: 'Yayımlanır...',
    processing: 'işlənir',
    upload_images: 'Şəkilləri yüklə',
    add_images_desc: 'Ən azı 3 şəkil əlavə edin. Sıralamaq üçün sürükləyin.',
    add_more_images: 'Daha {count} şəkil əlavə edin',
    ready_to_publish: 'Yayımlamağa hazırdır!',
    active_plan: 'Aktiv plan',
    search: 'Axtarış',
    enter_location: 'Yerləşməni daxil edin',
    search_city_district_or_address: 'Şəhər, rayon və ya ünvan yazın',
    screen_not_found: 'Ekran tapılmadı',
    listing_actions: 'Elan əməliyyatları',
    enter_value: 'Daxil edin...',
    select_brand: 'Marka seçin',
    search_brand: 'Marka axtarın',
    brand_required: 'Marka sahəsi mütləqdir.',
    district: 'Rayon',
    select_district: 'Rayonu seçin',
    select_city_first: 'Əvvəl şəhər seçin',
  },
  ru: {
    choose_language: 'Выберите язык',
    azerbaijani: 'Азербайджанский',
    russian: 'Русский',
    english: 'Английский',
    search_placeholder: 'Искать что угодно...',
    categories: 'Категории',
    recent_listings: 'Последние объявления',
    home: 'Главная',
    create: 'Создать',
    profile: 'Профиль',
    settings: 'Настройки',
    language: 'Язык',
    region: 'Регион',
    currency: 'Валюта',
    theme: 'Тема',
    notifications: 'Уведомления',
    help_support: 'Помощь и поддержка',
    about: 'О нас',
    log_out: 'Выйти',
    create_new_listing: 'Создать новое объявление',
    category: 'Категория',
    select_category: 'Выберите категорию',
    price: 'Цена',
    description: 'Описание',
    describe_item: 'Опишите ваш товар...',
    add_photos: 'Добавить фото',
    publish_listing: 'Опубликовать объявление',
    storage: 'Память',
    ram: 'ОЗУ',
    model: 'Модель',
    type: 'Тип',
    engineVolume: 'Объем двигателя',
    year: 'Год',
    mileage: 'Пробег',
    color: 'Цвет',
    condition: 'Состояние',
    delivery: 'Доставка',
    new: 'Новый',
    used: 'Б/у',
    available: 'Есть',
    not_available: 'Нет',
    black: 'Черный',
    white: 'Белый',
    silver: 'Серебристый',
    gold: 'Золотой',
    blue: 'Синий',
    red: 'Красный',
    green: 'Зеленый',
    gray: 'Серый',
    other: 'Другое',
    listings: 'Объявления',
    packages: 'Пакеты',
    stats: 'Статистика',
    next: 'Далее',
    skip: 'Пропустить',
    start_selling: 'Начать продавать',
    phone_number: 'Номер телефона',
    continue: 'Продолжить',
    verify: 'Подтвердить',
    enter_code: 'Введите код, отправленный на',
    resend_code: 'Отправить код снова',
    connect_platforms: 'Подключить платформы',
    connected: 'Подключено',
    connect: 'Подключить',
    success: 'Успешно!',
    listing_published: 'Ваше объявление успешно опубликовано.',
    view_listing: 'Посмотреть объявление',
    back_to_home: 'На главную',
    my_listings: 'Мои объявления',
    active: 'Активные',
    sold: 'Проданные',
    archived: 'В архиве',
    statistics: 'Статистика',
    total_views: 'Всего просмотров',
    total_likes: 'Всего лайков',
    total_messages: 'Всего сообщений',
    choose_plan: 'Выберите план',
    free: 'Бесплатно',
    premium: 'Премиум',
    pro: 'Про',
    select: 'Выбрать',
    current_plan: 'Текущий план',
    upgrade: 'Улучшить',
    cancel: 'Отмена',
    save: 'Сохранить',
    edit: 'Редактировать',
    delete: 'Удалить',
    confirm: 'Подтвердить',
    yes: 'Да',
    no: 'Нет',
    start_title: 'Продавайте свои товары на нескольких маркетплейсах с Salex.',
    start_subtitle: 'Опубликуйте один раз и автоматически делитесь везде.',
    start: 'НАЧАТЬ',
    create_account: 'Создать аккаунт',
    full_name: 'Полное имя',
    enter_full_name: 'Введите ваше полное имя',
    account_type: 'Тип аккаунта',
    individual_seller: 'Частный продавец',
    business_store: 'Бизнес-магазин',
    onboarding_title: 'Начните продавать проще с Salex.',
    onboarding_subtitle: 'Добавьте свой товар один раз и публикуйте везде.',
    connect_marketplaces: 'Подключить маркетплейсы',
    connect_platforms_subtitle: 'Подключите свои аккаунты маркетплейсов, чтобы начать автоматизацию.',
    available_platforms: 'Доступные платформы',
    ready_to_connect: 'Готово к подключению',
    coming_soon: 'Скоро',
    locked: 'Заблокировано',
    available_to_connect: 'Доступно для подключения',
    connect_your_account: 'Подключите ваш аккаунт',
    send_verification_code: 'Отправить код подтверждения',
    enter_verification_code: 'Введите код подтверждения',
    we_sent_code: 'Мы отправили 4-значный код на ваш телефон',
    connected_success: 'подключен',
    account_linked: 'Ваш аккаунт успешно привязан.',
    done: 'Готово',
    registration_completed: 'Регистрация завершена.',
    platforms_ready: 'Платформы готовы.',
    create_first_listing: 'Создайте свое первое объявление',
    city: 'Город',
    select_city: 'Выберите город',
    baku: 'Баку',
    ganja: 'Гянджа',
    sumqayit: 'Сумгаит',
    shaki: 'Шеки',
    lankaran: 'Ленкорань',
    images_upload: 'Загрузка изображений',
    share_platforms: 'Поделиться на платформах',
    model_name: 'Название модели',
    enter_model: 'Введите модель',
    brand_name: 'Название бренда',
    enter_brand: 'Введите бренд',
    congratulations: 'Поздравляем',
    go_to_dashboard: 'Перейти в панель управления',
    todays_limit: 'Лимит на сегодня',
    limit_reached: 'Лимит исчерпан',
    see_all: 'Смотреть все',
    no_listings_yet: 'Пока нет объявлений',
    create_first_listing_desc: 'Создайте свое первое объявление, чтобы начать продавать на платформах',
    reset_limit: 'Сбросить лимит (Debug)',
    todays_limit_reached: 'Лимит на сегодня исчерпан',
    limit_reached_desc: 'Вы достигли сегодняшнего лимита объявлений.',
    view_packages: 'Посмотреть пакеты',
    repost: 'Переопубликовать',
    choose_plan_desc: 'Выберите лучший план для ваших продаж.',
    basic_plan: 'Базовый',
    per_week: '/ неделя',
    listings_per_day: '3 объявления в день',
    activate: 'Активировать',
    popular: 'Популярный',
    premium_plan: 'Премиум',
    priority_posting: 'Приоритетное размещение',
    full_statistics: 'Полная статистика',
    auto_refresh: 'Автообновление объявлений',
    activate_premium: 'Активировать Премиум',
    premium_plus_plan: 'Премиум+',
    per_month: '/ месяц',
    unlimited_listings: 'Безлимитные объявления',
    all_platforms: 'Все платформы',
    business_tools: 'Бизнес-инструменты',
    activate_premium_plus: 'Активировать Премиум+',
    active_listings: 'Активные объявления',
    views_by_platform: 'Просмотры по платформам',
    top_performing: 'Самые популярные',
    views_this_week: 'просмотров на этой неделе',
    share_plan: 'План публикации',
    published_on: 'Ваше объявление будет опубликовано на',
    inactive: 'Неактивно',
    limit_indicator: 'Индикатор лимита:',
    listings_count: '1 / 3 объявлений',
    publishing: 'Публикация...',
    processing: 'в обработке',
    upload_images: 'Загрузить изображения',
    add_images_desc: 'Добавьте минимум 3 изображения. Перетащите для изменения порядка.',
    add_more_images: 'Добавьте еще {count} фото',
    ready_to_publish: 'Готово к публикации!',
    active_plan: 'Активный план',
    search: 'Поиск',
    enter_location: 'Введите местоположение',
    search_city_district_or_address: 'Введите город, район или адрес',
    screen_not_found: 'Экран не найден',
    listing_actions: 'Действия с объявлением',
    enter_value: 'Введите значение',
    select_brand: 'Выберите бренд',
    search_brand: 'Поиск бренда',
    brand_required: 'Поле бренда обязательно.',
    district: 'Район',
    select_district: 'Выберите район',
    select_city_first: 'Сначала выберите город',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('az');

  useEffect(() => {
    if (typeof document === 'undefined') {
      return;
    }

    document.documentElement.lang = language;
    document.documentElement.dataset.language = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
