export type AppLanguage = 'az' | 'ru' | 'en';

type Entry = Record<AppLanguage, string>;
export type CityOption = {
  code: string;
  label: Entry;
};

export const AZERBAIJAN_CITY_OPTIONS: CityOption[] = [
  { code: 'Baku', label: { az: 'Bakı', ru: 'Баку', en: 'Baku' } },
  { code: 'Ganja', label: { az: 'Gəncə', ru: 'Гянджа', en: 'Ganja' } },
  { code: 'Sumqayit', label: { az: 'Sumqayıt', ru: 'Сумгаит', en: 'Sumqayit' } },
  { code: 'Lankaran', label: { az: 'Lənkəran', ru: 'Ленкорань', en: 'Lankaran' } },
  { code: 'Shaki', label: { az: 'Şəki', ru: 'Шеки', en: 'Shaki' } },
  { code: 'Mingachevir', label: { az: 'Mingəçevir', ru: 'Мингечевир', en: 'Mingachevir' } },
  { code: 'Nakhchivan', label: { az: 'Naxçıvan', ru: 'Нахчыван', en: 'Nakhchivan' } },
  { code: 'Shirvan', label: { az: 'Şirvan', ru: 'Ширван', en: 'Shirvan' } },
  { code: 'Yevlakh', label: { az: 'Yevlax', ru: 'Евлах', en: 'Yevlakh' } },
  { code: 'Khirdalan', label: { az: 'Xırdalan', ru: 'Хырдалан', en: 'Khirdalan' } },
  { code: 'Khankendi', label: { az: 'Xankəndi', ru: 'Ханкенди', en: 'Khankendi' } },
  { code: 'Shusha', label: { az: 'Şuşa', ru: 'Шуша', en: 'Shusha' } },
  { code: 'Qabala', label: { az: 'Qəbələ', ru: 'Габала', en: 'Qabala' } },
  { code: 'Quba', label: { az: 'Quba', ru: 'Губа', en: 'Quba' } },
  { code: 'Qusar', label: { az: 'Qusar', ru: 'Гусар', en: 'Qusar' } },
  { code: 'Shamakhi', label: { az: 'Şamaxı', ru: 'Шемаха', en: 'Shamakhi' } },
  { code: 'Ismayilli', label: { az: 'İsmayıllı', ru: 'Исмаиллы', en: 'Ismayilli' } },
  { code: 'Zagatala', label: { az: 'Zaqatala', ru: 'Закаталы', en: 'Zagatala' } },
  { code: 'Balakan', label: { az: 'Balakən', ru: 'Белоканы', en: 'Balakan' } },
  { code: 'Gakh', label: { az: 'Qax', ru: 'Гах', en: 'Gakh' } },
  { code: 'Oghuz', label: { az: 'Oğuz', ru: 'Огуз', en: 'Oghuz' } },
  { code: 'Goygol', label: { az: 'Göygöl', ru: 'Гёйгёль', en: 'Goygol' } },
  { code: 'Tovuz', label: { az: 'Tovuz', ru: 'Товуз', en: 'Tovuz' } },
  { code: 'Gazakh', label: { az: 'Qazax', ru: 'Газах', en: 'Gazakh' } },
  { code: 'Agstafa', label: { az: 'Ağstafa', ru: 'Агстафа', en: 'Agstafa' } },
  { code: 'Gadabay', label: { az: 'Gədəbəy', ru: 'Гедабек', en: 'Gadabay' } },
  { code: 'Dashkasan', label: { az: 'Daşkəsən', ru: 'Дашкесан', en: 'Dashkasan' } },
  { code: 'Samukh', label: { az: 'Samux', ru: 'Самух', en: 'Samukh' } },
  { code: 'Agdash', label: { az: 'Ağdaş', ru: 'Агдаш', en: 'Agdash' } },
  { code: 'Agjabadi', label: { az: 'Ağcabədi', ru: 'Агджабеди', en: 'Agjabadi' } },
  { code: 'Agdam', label: { az: 'Ağdam', ru: 'Агдам', en: 'Agdam' } },
  { code: 'Barda', label: { az: 'Bərdə', ru: 'Барда', en: 'Barda' } },
  { code: 'Beylagan', label: { az: 'Beyləqan', ru: 'Бейлаган', en: 'Beylagan' } },
  { code: 'Bilasuvar', label: { az: 'Biləsuvar', ru: 'Билясувар', en: 'Bilasuvar' } },
  { code: 'Fuzuli', label: { az: 'Füzuli', ru: 'Физули', en: 'Fuzuli' } },
  { code: 'Horadiz', label: { az: 'Horadiz', ru: 'Горадиз', en: 'Horadiz' } },
  { code: 'Imishli', label: { az: 'İmişli', ru: 'Имишли', en: 'Imishli' } },
  { code: 'Kurdamir', label: { az: 'Kürdəmir', ru: 'Кюрдамир', en: 'Kurdamir' } },
  { code: 'Saatli', label: { az: 'Saatlı', ru: 'Саатлы', en: 'Saatli' } },
  { code: 'Sabirabad', label: { az: 'Sabirabad', ru: 'Сабирабад', en: 'Sabirabad' } },
  { code: 'Salyan', label: { az: 'Salyan', ru: 'Сальян', en: 'Salyan' } },
  { code: 'Neftchala', label: { az: 'Neftçala', ru: 'Нефтчала', en: 'Neftchala' } },
  { code: 'Hajigabul', label: { az: 'Hacıqabul', ru: 'Аджигабул', en: 'Hajigabul' } },
  { code: 'Jalilabad', label: { az: 'Cəlilabad', ru: 'Джалилабад', en: 'Jalilabad' } },
  { code: 'Masalli', label: { az: 'Masallı', ru: 'Масаллы', en: 'Masalli' } },
  { code: 'Lerik', label: { az: 'Lerik', ru: 'Лерик', en: 'Lerik' } },
  { code: 'Yardimli', label: { az: 'Yardımlı', ru: 'Ярдымлы', en: 'Yardimli' } },
  { code: 'Astara', label: { az: 'Astara', ru: 'Астара', en: 'Astara' } },
  { code: 'Qobustan', label: { az: 'Qobustan', ru: 'Гобустан', en: 'Qobustan' } },
  { code: 'Goychay', label: { az: 'Göyçay', ru: 'Гёйчай', en: 'Goychay' } },
  { code: 'Ujar', label: { az: 'Ucar', ru: 'Уджар', en: 'Ujar' } },
  { code: 'Zardab', label: { az: 'Zərdab', ru: 'Зардаб', en: 'Zardab' } },
  { code: 'Agsu', label: { az: 'Ağsu', ru: 'Агсу', en: 'Agsu' } },
  { code: 'Naftalan', label: { az: 'Naftalan', ru: 'Нафталан', en: 'Naftalan' } },
  { code: 'Kalbajar', label: { az: 'Kəlbəcər', ru: 'Кельбаджар', en: 'Kalbajar' } },
  { code: 'Lachin', label: { az: 'Laçın', ru: 'Лачин', en: 'Lachin' } },
  { code: 'Qubadli', label: { az: 'Qubadlı', ru: 'Кубатлы', en: 'Qubadli' } },
  { code: 'Zangilan', label: { az: 'Zəngilan', ru: 'Зангелан', en: 'Zangilan' } },
  { code: 'Jabrayil', label: { az: 'Cəbrayıl', ru: 'Джебраил', en: 'Jabrayil' } },
  { code: 'Khojaly', label: { az: 'Xocalı', ru: 'Ходжалы', en: 'Khojaly' } },
  { code: 'Khojavand', label: { az: 'Xocavənd', ru: 'Ходжавенд', en: 'Khojavand' } },
  { code: 'Tartar', label: { az: 'Tərtər', ru: 'Тертер', en: 'Tartar' } },
  { code: 'Goranboy', label: { az: 'Goranboy', ru: 'Горанбой', en: 'Goranboy' } },
  { code: 'Siyazan', label: { az: 'Siyəzən', ru: 'Сиазань', en: 'Siyazan' } },
  { code: 'Shabran', label: { az: 'Şabran', ru: 'Шабран', en: 'Shabran' } },
  { code: 'Absheron', label: { az: 'Abşeron', ru: 'Абшерон', en: 'Absheron' } },
];

const localizedText: Record<string, Entry> = {
  Elektronika: { az: 'Elektronika', ru: 'Электроника', en: 'Electronics' },
  'Telefonlar və aksesuarlar': { az: 'Telefonlar və aksesuarlar', ru: 'Телефоны и аксессуары', en: 'Phones and accessories' },
  Smartfonlar: { az: 'Smartfonlar', ru: 'Смартфоны', en: 'Smartphones' },
  'Düyməli telefonlar': { az: 'Düyməli telefonlar', ru: 'Кнопочные телефоны', en: 'Feature phones' },
  'Smart saatlar və qolbaqlar': { az: 'Smart saatlar və qolbaqlar', ru: 'Смарт-часы и браслеты', en: 'Smart watches and bands' },
  Qulaqlıqlar: { az: 'Qulaqlıqlar', ru: 'Наушники', en: 'Headphones' },
  'Telefon aksesuarları': { az: 'Telefon aksesuarları', ru: 'Аксессуары для телефонов', en: 'Phone accessories' },
  'Planşetlər': { az: 'Planşetlər', ru: 'Планшеты', en: 'Tablets' },
  Noutbuklar: { az: 'Noutbuklar', ru: 'Ноутбуки', en: 'Laptops' },
  Televizorlar: { az: 'Televizorlar', ru: 'Телевизоры', en: 'TVs' },
  'Audio sistemlər və dinamiklər': { az: 'Audio sistemlər və dinamiklər', ru: 'Аудиосистемы и колонки', en: 'Audio systems and speakers' },
  'Oyun konsolları və oyun aksesuarları': { az: 'Oyun konsolları və oyun aksesuarları', ru: 'Игровые консоли и аксессуары', en: 'Gaming consoles and accessories' },
  'Fotoaparatlar və videokameralar': { az: 'Fotoaparatlar və videokameralar', ru: 'Фотоаппараты и видеокамеры', en: 'Cameras and camcorders' },
  'Daşınmaz əmlak': { az: 'Daşınmaz əmlak', ru: 'Недвижимость', en: 'Real estate' },
  Nəqliyyat: { az: 'Nəqliyyat', ru: 'Транспорт', en: 'Vehicles' },
  'Mənzillər': { az: 'Mənzillər', ru: 'Квартиры', en: 'Apartments' },
  'Villalar, bağ evləri': { az: 'Villalar, bağ evləri', ru: 'Виллы, дачи', en: 'Villas and country houses' },
  Torpaq: { az: 'Torpaq', ru: 'Земельные участки', en: 'Land' },
  'Obyektlər və ofislər': { az: 'Obyektlər və ofislər', ru: 'Коммерческие объекты и офисы', en: 'Commercial properties and offices' },
  Qarajlar: { az: 'Qarajlar', ru: 'Гаражи', en: 'Garages' },
  Satılır: { az: 'Satılır', ru: 'Продажа', en: 'For sale' },
  'Kirayə (uzunmüddətli)': { az: 'Kirayə (uzunmüddətli)', ru: 'Аренда (долгосрочная)', en: 'Long-term rent' },
  'Kirayə': { az: 'Kirayə', ru: 'Аренда', en: 'Rent' },
  Avtomobillər: { az: 'Avtomobillər', ru: 'Автомобили', en: 'Cars' },
  'Motosikletlər və mopedlər': { az: 'Motosikletlər və mopedlər', ru: 'Мотоциклы и мопеды', en: 'Motorcycles and mopeds' },
  'Ehtiyat hissələri və aksesuarlar': { az: 'Ehtiyat hissələri və aksesuarlar', ru: 'Запчасти и аксессуары', en: 'Spare parts and accessories' },
  'Digər model': { az: 'Digər model', ru: 'Другая модель', en: 'Other model' },
  'Digər marka': { az: 'Digər marka', ru: 'Другой бренд', en: 'Other brand' },
  'Digər aksesuar': { az: 'Digər aksesuar', ru: 'Другой аксессуар', en: 'Other accessory' },
  Digər: { az: 'Digər', ru: 'Другое', en: 'Other' },
  'Qablar və qoruyucular': { az: 'Qablar və qoruyucular', ru: 'Чехлы и защита', en: 'Cases and protection' },
  'Şarj cihazları və kabellər': { az: 'Şarj cihazları və kabellər', ru: 'Зарядные устройства и кабели', en: 'Chargers and cables' },
  Marka: { az: 'Marka', ru: 'Бренд', en: 'Brand' },
  'Marka seçin': { az: 'Marka seçin', ru: 'Выберите бренд', en: 'Select brand' },
  'Marka axtarın': { az: 'Marka axtarın', ru: 'Поиск бренда', en: 'Search brand' },
  Rayon: { az: 'Rayon', ru: 'Район', en: 'District' },
  'Rayonu seçin': { az: 'Rayonu seçin', ru: 'Выберите район', en: 'Select district' },
  'Əvvəl şəhər seçin': { az: 'Əvvəl şəhər seçin', ru: 'Сначала выберите город', en: 'Select a city first' },
  'Malın növü': { az: 'Malın növü', ru: 'Тип товара', en: 'Item type' },
  'Malın növünü seçin': { az: 'Malın növünü seçin', ru: 'Выберите тип товара', en: 'Select item type' },
  Model: { az: 'Model', ru: 'Модель', en: 'Model' },
  'Modeli yazın': { az: 'Modeli yazın', ru: 'Введите модель', en: 'Enter model' },
  'Mühərrikin həcmi, sm³': { az: 'Mühərrikin həcmi, sm³', ru: 'Объем двигателя, см³', en: 'Engine volume, cm³' },
  'Buraxılış ili': { az: 'Buraxılış ili', ru: 'Год выпуска', en: 'Year' },
  'Yürüşü, km': { az: 'Yürüşü, km', ru: 'Пробег, км', en: 'Mileage, km' },
  'Yeni?': { az: 'Yeni?', ru: 'Новый?', en: 'New?' },
  'Marka sahəsi mütləqdir.': { az: 'Marka sahəsi mütləqdir.', ru: 'Поле бренда обязательно.', en: 'Brand is required.' },
  'Model sahəsi mütləqdir.': { az: 'Model sahəsi mütləqdir.', ru: 'Поле модели обязательно.', en: 'Model is required.' },
  'Malın növü sahəsi mütləqdir.': { az: 'Malın növü sahəsi mütləqdir.', ru: 'Поле типа товара обязательно.', en: 'Item type is required.' },
  'Mühərrikin həcmi sahəsi mütləqdir.': { az: 'Mühərrikin həcmi sahəsi mütləqdir.', ru: 'Поле объема двигателя обязательно.', en: 'Engine volume is required.' },
  'Buraxılış ili sahəsi mütləqdir.': { az: 'Buraxılış ili sahəsi mütləqdir.', ru: 'Поле года выпуска обязательно.', en: 'Year is required.' },
  'Yürüşü sahəsi mütləqdir.': { az: 'Yürüşü sahəsi mütləqdir.', ru: 'Поле пробега обязательно.', en: 'Mileage is required.' },
  'Mühərrik hissələri': { az: 'Mühərrik hissələri', ru: 'Детали двигателя', en: 'Engine parts' },
  'Kuzov hissələri': { az: 'Kuzov hissələri', ru: 'Кузовные детали', en: 'Body parts' },
  'Elektrik hissələri': { az: 'Elektrik hissələri', ru: 'Электрические детали', en: 'Electrical parts' },
  'Təkər və disklər': { az: 'Təkər və disklər', ru: 'Шины и диски', en: 'Wheels and rims' },
  'Yağlar və mayelər': { az: 'Yağlar və mayelər', ru: 'Масла и жидкости', en: 'Oils and fluids' },
  Kateqoriya: { az: 'Kateqoriya', ru: 'Категория', en: 'Category' },
  'Kateqoriyanı seçin': { az: 'Kateqoriyanı seçin', ru: 'Выберите категорию', en: 'Select category' },
  'Marka uyğunluğu': { az: 'Marka uyğunluğu', ru: 'Совместимый бренд', en: 'Compatible brand' },
  'Model uyğunluğu': { az: 'Model uyğunluğu', ru: 'Совместимая модель', en: 'Compatible model' },
  'Məhsul adı': { az: 'Məhsul adı', ru: 'Название товара', en: 'Product name' },
  Vəziyyət: { az: 'Vəziyyət', ru: 'Состояние', en: 'Condition' },
  Çatdırılma: { az: 'Çatdırılma', ru: 'Доставка', en: 'Delivery' },
  'Modeli əl ilə daxil edin': { az: 'Modeli əl ilə daxil edin', ru: 'Ввести модель вручную', en: 'Enter model manually' },
  'Modeli əl ilə daxil et': { az: 'Modeli əl ilə daxil et', ru: 'Ввести модель вручную', en: 'Enter model manually' },
  'Məhsul adını yazın': { az: 'Məhsul adını yazın', ru: 'Введите название товара', en: 'Enter product name' },
  'Vəziyyəti seçin': { az: 'Vəziyyəti seçin', ru: 'Выберите состояние', en: 'Select condition' },
  'Çatdırılma seçin': { az: 'Çatdırılma seçin', ru: 'Выберите доставку', en: 'Select delivery' },
  'Ehtiyat hissələri sistemi': { az: 'Ehtiyat hissələri sistemi', ru: 'Система запчастей', en: 'Parts system' },
  'Uyğunluq və məhsul detalları': { az: 'Uyğunluq və məhsul detalları', ru: 'Совместимость и детали товара', en: 'Compatibility and product details' },
  'Bölmə, uyğun marka-model və çatdırılma məlumatı marketplace səviyyəsində toplanır.': {
    az: 'Bölmə, uyğun marka-model və çatdırılma məlumatı marketplace səviyyəsində toplanır.',
    ru: 'Раздел, совместимые бренд и модель, а также информация о доставке собираются на уровне маркетплейса.',
    en: 'Section, compatible brand-model, and delivery information are collected at the marketplace level.',
  },
  Hazırlıq: { az: 'Hazırlıq', ru: 'Готовность', en: 'Readiness' },
  Ağ: { az: 'Ağ', ru: 'Белый', en: 'White' },
  Qara: { az: 'Qara', ru: 'Черный', en: 'Black' },
  Boz: { az: 'Boz', ru: 'Серый', en: 'Gray' },
  Gümüşü: { az: 'Gümüşü', ru: 'Серебристый', en: 'Silver' },
  Göy: { az: 'Göy', ru: 'Синий', en: 'Blue' },
  Qırmızı: { az: 'Qırmızı', ru: 'Красный', en: 'Red' },
  Yaşıl: { az: 'Yaşıl', ru: 'Зеленый', en: 'Green' },
  Bej: { az: 'Bej', ru: 'Бежевый', en: 'Beige' },
  Qəhvəyi: { az: 'Qəhvəyi', ru: 'Коричневый', en: 'Brown' },
  Narıncı: { az: 'Narıncı', ru: 'Оранжевый', en: 'Orange' },
  Benzin: { az: 'Benzin', ru: 'Бензин', en: 'Petrol' },
  Dizel: { az: 'Dizel', ru: 'Дизель', en: 'Diesel' },
  Hibrid: { az: 'Hibrid', ru: 'Гибрид', en: 'Hybrid' },
  'Plug-in Hibrid': { az: 'Plug-in Hibrid', ru: 'Подключаемый гибрид', en: 'Plug-in hybrid' },
  Elektrik: { az: 'Elektrik', ru: 'Электро', en: 'Electric' },
  Qaz: { az: 'Qaz', ru: 'Газ', en: 'Gas' },
  Avtomat: { az: 'Avtomat', ru: 'Автомат', en: 'Automatic' },
  Mexaniki: { az: 'Mexaniki', ru: 'Механика', en: 'Manual' },
  Robotlaşdırılmış: { az: 'Robotlaşdırılmış', ru: 'Роботизированная', en: 'Robotized' },
  Variator: { az: 'Variator', ru: 'Вариатор', en: 'CVT' },
  Hetçbek: { az: 'Hetçbek', ru: 'Хэтчбек', en: 'Hatchback' },
  Liftbek: { az: 'Liftbek', ru: 'Лифтбек', en: 'Liftback' },
  Universal: { az: 'Universal', ru: 'Универсал', en: 'Wagon' },
  Kupe: { az: 'Kupe', ru: 'Купе', en: 'Coupe' },
  Kabriolet: { az: 'Kabriolet', ru: 'Кабриолет', en: 'Convertible' },
  Pikap: { az: 'Pikap', ru: 'Пикап', en: 'Pickup' },
  Miniven: { az: 'Miniven', ru: 'Минивэн', en: 'Minivan' },
  Rəng: { az: 'Rəng', ru: 'Цвет', en: 'Color' },
  'Mühərrik (sm³)': { az: 'Mühərrik (sm³)', ru: 'Двигатель (см³)', en: 'Engine (cm³)' },
  'Yanacaq növü': { az: 'Yanacaq növü', ru: 'Тип топлива', en: 'Fuel type' },
  'Sürətlər qutusu': { az: 'Sürətlər qutusu', ru: 'Коробка передач', en: 'Transmission' },
  'Kuzov növü': { az: 'Kuzov növü', ru: 'Тип кузова', en: 'Body type' },
  'Rəng seçin': { az: 'Rəng seçin', ru: 'Выберите цвет', en: 'Select color' },
  'Yanacaq növünü seçin': { az: 'Yanacaq növünü seçin', ru: 'Выберите тип топлива', en: 'Select fuel type' },
  'Sürətlər qutusunu seçin': { az: 'Sürətlər qutusunu seçin', ru: 'Выберите коробку передач', en: 'Select transmission' },
  'Kuzov növünü seçin': { az: 'Kuzov növünü seçin', ru: 'Выберите тип кузова', en: 'Select body type' },
  'Məsələn, 1998': { az: 'Məsələn, 1998', ru: 'Например, 1998', en: 'For example, 1998' },
  'Məsələn, 2020': { az: 'Məsələn, 2020', ru: 'Например, 2020', en: 'For example, 2020' },
  Motosiklet: { az: 'Motosiklet', ru: 'Мотоцикл', en: 'Motorcycle' },
  Moped: { az: 'Moped', ru: 'Мопед', en: 'Moped' },
  Skuter: { az: 'Skuter', ru: 'Скутер', en: 'Scooter' },
  Kvadrotsikl: { az: 'Kvadrotsikl', ru: 'Квадроцикл', en: 'ATV' },
  Yeni: { az: 'Yeni', ru: 'Новый', en: 'New' },
  'İşlənmiş': { az: 'İşlənmiş', ru: 'Б/у', en: 'Used' },
  'Çatdırılma var': { az: 'Çatdırılma var', ru: 'Есть доставка', en: 'Delivery available' },
  'Çatdırılma yoxdur': { az: 'Çatdırılma yoxdur', ru: 'Нет доставки', en: 'No delivery' },
  'Növ': { az: 'Növ', ru: 'Тип', en: 'Type' },
  'Tutum': { az: 'Tutum', ru: 'Вместимость', en: 'Capacity' },
  'Sıxma sürəti': { az: 'Sıxma sürəti', ru: 'Скорость отжима', en: 'Spin speed' },
  'Tutum (komplekt)': { az: 'Tutum (komplekt)', ru: 'Вместимость (комплектов)', en: 'Capacity (sets)' },
  BTU: { az: 'BTU', ru: 'BTU', en: 'BTU' },
  'Sahə (m²)': { az: 'Sahə (m²)', ru: 'Площадь (м²)', en: 'Area (m²)' },
  'Güc (W)': { az: 'Güc (W)', ru: 'Мощность (Вт)', en: 'Power (W)' },
  'Toz toplayıcı': { az: 'Toz toplayıcı', ru: 'Пылесборник', en: 'Dust collector' },
  'Həcm (L)': { az: 'Həcm (L)', ru: 'Объем (л)', en: 'Volume (L)' },
  'Elanın növü': { az: 'Elanın növü', ru: 'Тип объявления', en: 'Listing type' },
  Yerləşmə: { az: 'Yerləşmə', ru: 'Расположение', en: 'Location' },
  'Yerləşməni daxil edin': { az: 'Yerləşməni daxil edin', ru: 'Введите местоположение', en: 'Enter location' },
  'Şəhər, rayon və ya ünvan yazın': { az: 'Şəhər, rayon və ya ünvan yazın', ru: 'Введите город, район или адрес', en: 'Enter city, district, or address' },
  'Otaq sayı': { az: 'Otaq sayı', ru: 'Количество комнат', en: 'Room count' },
  'Mərtəbə': { az: 'Mərtəbə', ru: 'Этаж', en: 'Floor' },
  'Mərtəbə sayı': { az: 'Mərtəbə sayı', ru: 'Количество этажей', en: 'Number of floors' },
  Təmir: { az: 'Təmir', ru: 'Ремонт', en: 'Renovation' },
  'Təmirli': { az: 'Təmirli', ru: 'С ремонтом', en: 'Renovated' },
  'Təmirsiz': { az: 'Təmirsiz', ru: 'Без ремонта', en: 'Without renovation' },
  'Əlavə': { az: 'Əlavə', ru: 'Дополнительно', en: 'Additional features' },
  'Sahəni daxil edin': { az: 'Sahəni daxil edin', ru: 'Введите площадь', en: 'Enter area' },
  'Sahəni daxil edin (m²)': { az: 'Sahəni daxil edin (m²)', ru: 'Введите площадь (м²)', en: 'Enter area (m²)' },
  'Torpaq sahəsi': { az: 'Torpaq sahəsi', ru: 'Площадь участка', en: 'Land area' },
  'Obyektin növü': { az: 'Obyektin növü', ru: 'Тип объекта', en: 'Property type' },
  Təyinatı: { az: 'Təyinatı', ru: 'Назначение', en: 'Purpose' },
  Sənədlər: { az: 'Sənədlər', ru: 'Документы', en: 'Documents' },
  'Növü': { az: 'Növü', ru: 'Тип', en: 'Type' },
  'Vəziyyəti': { az: 'Vəziyyəti', ru: 'Состояние', en: 'Condition' },
  Mülkiyyətçi: { az: 'Mülkiyyətçi', ru: 'Собственник', en: 'Owner' },
  'Soyuducu növü': { az: 'Soyuducu növü', ru: 'Тип холодильника', en: 'Refrigerator type' },
  Həcm: { az: 'Həcm', ru: 'Объем', en: 'Volume' },
  'Enerji sinfi': { az: 'Enerji sinfi', ru: 'Энергокласс', en: 'Energy class' },
  'Fotoaparat': { az: 'Fotoaparat', ru: 'Фотоаппарат', en: 'Camera' },
  Videokamera: { az: 'Videokamera', ru: 'Видеокамера', en: 'Camcorder' },
  'Action kamera': { az: 'Action kamera', ru: 'Экшн-камера', en: 'Action camera' },
  'Vlog kamera': { az: 'Vlog kamera', ru: 'Влог-камера', en: 'Vlog camera' },
  '360 kamera': { az: '360 kamera', ru: '360 камера', en: '360 camera' },
  'Bluetooth speaker': { az: 'Bluetooth speaker', ru: 'Bluetooth-колонка', en: 'Bluetooth speaker' },
  'Home speaker': { az: 'Home speaker', ru: 'Домашняя колонка', en: 'Home speaker' },
  Soundbar: { az: 'Soundbar', ru: 'Саундбар', en: 'Soundbar' },
  Subwoofer: { az: 'Subwoofer', ru: 'Сабвуфер', en: 'Subwoofer' },
  Headphones: { az: 'Headphones', ru: 'Наушники', en: 'Headphones' },
  Earbuds: { az: 'Earbuds', ru: 'Вкладыши', en: 'Earbuds' },
  Microphone: { az: 'Microphone', ru: 'Микрофон', en: 'Microphone' },
  Qoşulma: { az: 'Qoşulma', ru: 'Подключение', en: 'Connection' },
  'Güc / Çıxış': { az: 'Güc / Çıxış', ru: 'Мощность / выход', en: 'Power / output' },
  'Tək qapılı': { az: 'Tək qapılı', ru: 'Однодверный', en: 'Single door' },
  'Iki qapili': { az: 'Iki qapili', ru: 'Двухдверный', en: 'Double door' },
  'İki qapılı': { az: 'İki qapılı', ru: 'Двухдверный', en: 'Double door' },
  'Mini soyuducu': { az: 'Mini soyuducu', ru: 'Мини-холодильник', en: 'Mini fridge' },
  'No-frost': { az: 'No-frost', ru: 'No Frost', en: 'No Frost' },
  Qoşulub: { az: 'Qoşulub', ru: 'Подключено', en: 'Connected' },
  Qoşulmayıb: { az: 'Qoşulmayıb', ru: 'Не подключено', en: 'Not connected' },
  'Keç': { az: 'Keç', ru: 'Пропустить', en: 'Skip' },
  'Təsdiqlə': { az: 'Təsdiqlə', ru: 'Подтвердить', en: 'Confirm' },
  'Daxil edin...': { az: 'Daxil edin...', ru: 'Введите значение...', en: 'Enter value...' },
  Yasamal: { az: 'Yasamal', ru: 'Ясамал', en: 'Yasamal' },
  'Nərimanov': { az: 'Nərimanov', ru: 'Нариманов', en: 'Narimanov' },
  'Nəsimi': { az: 'Nəsimi', ru: 'Насими', en: 'Nasimi' },
  'Xətai': { az: 'Xətai', ru: 'Хатаи', en: 'Khatai' },
  'Binəqədi': { az: 'Binəqədi', ru: 'Бинагади', en: 'Binagadi' },
  'Səbail': { az: 'Səbail', ru: 'Сабаил', en: 'Sabail' },
  'Kəpəz': { az: 'Kəpəz', ru: 'Кяпаз', en: 'Kapaz' },
  Nizami: { az: 'Nizami', ru: 'Низами', en: 'Nizami' },
  '1-ci mikrorayon': { az: '1-ci mikrorayon', ru: '1-й микрорайон', en: '1st microdistrict' },
  '2-ci mikrorayon': { az: '2-ci mikrorayon', ru: '2-й микрорайон', en: '2nd microdistrict' },
  Corat: { az: 'Corat', ru: 'Джорат', en: 'Corat' },
  'Mərkəz': { az: 'Mərkəz', ru: 'Центр', en: 'Center' },
  'Aşağı Göynük': { az: 'Aşağı Göynük', ru: 'Ашага Гейнюк', en: 'Ashagi Goynuk' },
  Kiş: { az: 'Kiş', ru: 'Киш', en: 'Kish' },
  Liman: { az: 'Liman', ru: 'Лиман', en: 'Liman' },
  Girdəni: { az: 'Girdəni', ru: 'Гирдяни', en: 'Girdani' },
  Controller: { az: 'Controller', ru: 'Контроллер', en: 'Controller' },
  Headset: { az: 'Headset', ru: 'Гарнитура', en: 'Headset' },
  'VR accessory': { az: 'VR accessory', ru: 'VR-аксессуар', en: 'VR accessory' },
  'Charging dock': { az: 'Charging dock', ru: 'Зарядная станция', en: 'Charging dock' },
  'Racing wheel': { az: 'Racing wheel', ru: 'Гоночный руль', en: 'Racing wheel' },
  Mouse: { az: 'Mouse', ru: 'Мышь', en: 'Mouse' },
  Keyboard: { az: 'Keyboard', ru: 'Клавиатура', en: 'Keyboard' },
};

const localizedAliases: Record<string, Entry> = Object.entries(localizedText).reduce<Record<string, Entry>>((accumulator, [key, entry]) => {
  accumulator[key] = entry;
  accumulator[entry.az] = entry;
  accumulator[entry.ru] = entry;
  accumulator[entry.en] = entry;
  return accumulator;
}, {});

const corruptedAliases: Record<string, string> = {
  '?n y?kl?m?li': 'Ön yükləməli',
  '�std?n y?kl?m?li': 'Üstdən yükləməli',
  'Dig?r': 'Digər',
  '3�5 kq': '3-5 kq',
  '5�7 kq': '5-7 kq',
  '7�9 kq': '7-9 kq',
  'Qurasdirilan': 'Quraşdırılan',
  'Ayri dayanan': 'Ayrı dayanan',
  'Stol?st?': 'Stolüstü',
  '6�8': '6-8',
  '9�11': '9-11',
  '12�14': '12-14',
  'P?nc?r?': 'Pəncərə',
  'Kis?li': 'Kisəli',
  'Konteynerli': 'Konteynerli',
  'Akvafiltrli': 'Akvafiltrli',
  'Sade': 'Sadə',
  'Qril il?': 'Qril ilə',
  'Konveksiyali': 'Konveksiyalı',
  '?aydan': 'Çaydan',
  '?t??k?n masin': 'Ətçəkən maşın',
  'Q?hv?bisir?n': 'Qəhvəbişirən',
  'Satilir': 'Satılır',
  'Kiray? (uzunm?dd?tli)': 'Kirayə (uzunmüddətli)',
  '1 otaqli': '1 otaqlı',
  '2 otaqli': '2 otaqlı',
  '3 otaqli': '3 otaqlı',
  '4 otaqli': '4 otaqlı',
  '5+ otaqli': '5+ otaqlı',
  '1�5': '1-5',
  '5�10': '5-10',
  '?syali': 'Əşyalı',
  'H?y?t': 'Həyət',
  'Hovuz': 'Hovuz',
  'Kup?a': 'Kupça',
  'Magaza': 'Mağaza',
  'Kup�a var': 'Kupça var',
  'Kup�a yoxdur': 'Kupça yoxdur',
  'A�iq': 'Açıq',
  'Qapali': 'Qapalı',
  'Yeralti': 'Yeraltı',
  'T?k qapili': 'Tək qapılı',
  'Iki qapili': 'İki qapılı',
  '0�100 L': '0-100 L',
  '100�200 L': '100-200 L',
  '200�300 L': '200-300 L',
  '300�400 L': '300-400 L',
  '0�20 W': '0-20 W',
  '20�50 W': '20-50 W',
  '50�100 W': '50-100 W',
};

const pathSeparatorPattern = /\s+→\s+/;

export const localizeListingText = (value: string, language: AppLanguage): string => {
  if (!value) {
    return value;
  }

  const normalized = corruptedAliases[value] ?? value;
  return localizedAliases[normalized]?.[language] ?? normalized;
};

export const localizeListingPath = (value: string, language: AppLanguage): string => {
  if (!value) {
    return value;
  }

  return value
    .split(pathSeparatorPattern)
    .map((segment) => localizeListingText(segment.trim(), language))
    .join(' → ');
};

export const localizeListingSegments = (segments: string[], language: AppLanguage): string[] =>
  segments.map((segment) => localizeListingText(segment, language));

export const localizeDomText = (value: string, language: AppLanguage): string => {
  if (!value) {
    return value;
  }

  if (value.includes('→')) {
    return localizeListingPath(value, language);
  }

  return localizeListingText(value, language);
};

export const localizeCityCode = (city: string, language: AppLanguage): string => {
  return AZERBAIJAN_CITY_OPTIONS.find((option) => option.code === city)?.label[language] ?? city;
};
